include:
  - networks/wpan_simulation.yaml

name: coap-d1

services:
  coap-server:
    extends:
      file: coap/coap_server.yaml
      service: coap-server-base
    networks:
      wpan_simulation:
        aliases:
          - dns-server
    environment:
      BIND_PREFIX: "${WPAN_SIMULATION_PREFIX}"
  coap-client:
    extends:
      file: coap/coap_client.yaml
      service: coap-client-base
    depends_on:
      sniffer:
        condition: service_started
    environment:
      COAP_SERVER: "coap-server"
      DNS_SERVER: "dns-server"
      NETWORK_SCENARIO: "coap-d1"
  sniffer:
    extends:
      file: sniffer/sniffer.yaml
      service: sniffer-base
    environment:
      SNIFFER_IFACE: "${WPAN_SIMULATION_IFACE}"
      SNIFFER_FILTER: "udp port 5683 or udp port 5684"
      NETWORK_SCENARIO: "coap-d1"
    depends_on:
      coap-server:
        condition: service_started
