include:
  - networks/database_backend.yaml
  - networks/wpan_simulation.yaml

name: coap-d1

services:
  db:
    extends:
      file: database/database.yaml
      service: db-base
  coap-server-global:
    extends:
      file: coap/coap_server.yaml
      service: coap-server-base
    networks:
      wpan_simulation:
        aliases:
          - dns-server
          # need to trick docker-compose to use the hostname over this network instead of
          # database_backend
          - coap-server
    depends_on:
      db:
        condition: service_healthy
    environment:
      BIND_PREFIX: "${WPAN_SIMULATION_PREFIX}"
      SERVER_CREDENTIALS: "${DATA_SERVER_CREDENTIALS:-}"
      NETWORK_SCENARIO: "coap-d1"
  coap-client:
    extends:
      file: coap/coap_client.yaml
      service: coap-client-base
    depends_on:
      sniffer:
        condition: service_started
    environment:
      COAP_SERVER: "coap-server"
      DNS_SERVER: "coap-server"
      NETWORK_SCENARIO: "coap-d1"
  sniffer:
    extends:
      file: sniffer/sniffer.yaml
      service: sniffer-base
    environment:
      SNIFFER_IFACE: "${WPAN_SIMULATION_IFACE}"
      SNIFFER_LOGNAME: wpan
      SNIFFER_FILTER: "udp port 5683 or udp port 5684"
      NETWORK_SCENARIO: "coap-d1"
    depends_on:
      coap-server-global:
        condition: service_started
