# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.

services:
  coap-base:
    build:
      args:
        HOST_GID: "${HOST_GID}"
        HOST_UID: "${HOST_UID}"
      context: .
      dockerfile: Dockerfile
      target: coap-base
    sysctls:
      net.ipv6.auto_flowlabels: 0
    image: miri64/eurosp26-coap
    tmpfs:
      - /creds
    volumes:
      - ../:/app
