# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.

include:
  - networks/database_backend.yaml
  - networks/wpan_simulation.yaml
  - networks/upstream.yaml

name: coap-p2

services:
  db:
    extends:
      file: database/database.yaml
      service: db-base
  coap-server-global:
    extends:
      file: coap/coap_server.yaml
      service: coap-server-base
    networks:
      upstream:
        aliases:
          # need to trick docker-compose to use the hostname over this network instead of
          # database_backend
          - coap-server
    environment:
      BIND_PREFIX: "${UPSTREAM_PREFIX}"
      SERVER_CREDENTIALS: "${DATA_SERVER_CREDENTIALS:-}"
      NETWORK_SCENARIO: "coap-p2"
      SERVER_NAME: "coap-server"
    depends_on:
      db:
        condition: service_healthy
  dns-server-global:
    extends:
      file: coap/coap_server.yaml
      service: coap-server-base
    networks:
      upstream:
        aliases:
          # need to trick docker-compose to use the hostname over this network instead of
          # database_backend
          - dns-server
    environment:
      BIND_PREFIX: "${UPSTREAM_PREFIX}"
      SERVER_CREDENTIALS: "${DNS_SERVER_CREDENTIALS:-}"
      NETWORK_SCENARIO: "coap-p2"
      SERVER_NAME: "dns-server"
    depends_on:
      db:
        condition: service_healthy
  coap-proxy-global:
    extends:
      file: coap/coap_proxy.yaml
      service: coap-proxy-base
    networks:
      upstream:
      wpan_simulation:
        aliases:
          # need to trick docker-compose to use the hostname over this network instead of
          # database_backend
          - coap-proxy
    environment:
      BIND_PREFIX: "${WPAN_SIMULATION_PREFIX}"
      NETWORK_SCENARIO: "coap-p2"
    depends_on:
      coap-server-global:
        condition: service_started
      dns-server-global:
        condition: service_started
  coap-client:
    extends:
      file: coap/coap_client.yaml
      service: coap-client-base
    depends_on:
      sniffer-wpan:
        condition: service_started
    environment:
      CLIENT_PROXY_CREDENTIALS: "${CLIENT_PROXY_CREDENTIALS:-}"
      PROXY: "coap-proxy"
      COAP_SERVER: "coap-server"
      DNS_SERVER: "dns-server"
      NETWORK_SCENARIO: "coap-p2"
  sniffer-wpan:
    extends:
      file: sniffer/sniffer.yaml
      service: sniffer-base
    environment:
      SNIFFER_IFACE: "${WPAN_SIMULATION_IFACE}"
      SNIFFER_LOGNAME: wpan
      SNIFFER_FILTER: "udp port 5683 or udp port 5684"
      NETWORK_SCENARIO: "coap-p2"
    depends_on:
      coap-proxy-global:
        condition: service_started
  sniffer-upstream:
    extends:
      file: sniffer/sniffer.yaml
      service: sniffer-base
    environment:
      SNIFFER_IFACE: "${UPSTREAM_IFACE}"
      SNIFFER_LOGNAME: upstream
      SNIFFER_FILTER: "udp port 5683 or udp port 5684"
      NETWORK_SCENARIO: "coap-p2"
    depends_on:
      coap-server-global:
        condition: service_started
      dns-server-global:
        condition: service_started
