services:
  sniffer-base:
    build:
      args:
        HOST_GID: "${HOST_GID}"
        HOST_UID: "${HOST_UID}"
      context: .
      dockerfile: Dockerfile
    image: pivot-eval/sniffer
    volumes:
      - ../../output_dataset:/dumps/
      - ./:/app
    network_mode: host
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      DATA_FORMAT: "${DATA_FORMAT}"
      DNS_FORMAT: "${DNS_FORMAT}"
      BLOCK_SIZE: "${BLOCK_SIZE:-}"
      SECURITY: "${SECURITY:-}"
      SCHC_RULES_MODE: "${SCHC_RULES_MODE:-}"
    command: |
      /app/sniffer.sh
    healthcheck:
      test: ["CMD", "pgrep", "tshark"]
      interval: 10m
      timeout: 10s
      retries: 60
      start_period: 5m
      start_interval: 1s
