# Copyright (C) 2025 TU Dresden
#
# Distributed under terms of the MIT license.

include:
  - ../networks/database_backend.yaml

services:
  db-base:
    image: miri64/eurosp26-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: "not_a_big_secret"
    networks:
      - database_backend
    volumes:
      - .:/docker-entrypoint-initdb.d/
      - ../../jsons:/sqlite/
    healthcheck:
      test: ["CMD", "psql", "-v", "ON_ERROR_STOP=1", "--username", 'postgres', "--dbname", 'postgres', "-c", "SELECT COUNT(*) FROM synced_dns;"]
      interval: 10m
      timeout: 10s
      retries: 60
      start_period: 5m
      start_interval: 10s
