services:
  coap-base:
    build:
      args:
        HOST_GID: "${HOST_GID}"
        HOST_UID: "${HOST_UID}"
      context: .
      dockerfile: Dockerfile
    image:
      pivot-eval/coap
    tmpfs:
      - /creds
    volumes:
      - ../:/app
