services:
  coap-base:
    build:
      args:
        HOST_GID: "${HOST_GID}"
        HOST_UID: "${HOST_UID}"
      context: .
      dockerfile: Dockerfile
      target: coap-base
    sysctls:
      net.ipv6.auto_flowlabels: 0
    image:
      pivot-eval/coap
    tmpfs:
      - /creds
    volumes:
      - ../:/app
